### ISSUE TITLE
vcn LC use cases: check LC version as first step

### ISSUE THREAD

**Issue by Giako** [codenotary/vcn#110]
The version check should ensure that vcn is interacting with the right version of LC backend.

If the check fails, show a warning to the user.

The version check depends on [this LC issue](https://github.com/vchain-us/ledger-compliance/issues/188).

**Comment by dmacvicar** [comment]
I think we can close this one now (@mmeloni )

**Comment by dmacvicar** [comment]
I think we can close this one now that master sends the header (@mmeloni ?)
