### ISSUE TITLE
LC vs blockchain - VCN UX improvements

### ISSUE THREAD

**Issue by mmeloni** [codenotary/vcn#134]
**What would you like to be added or enhanced**
* failed vcn login to LC, you are still logged into the blockchain.
* failed vcn login to cn.io, you are still logged into LC.

**Why is this needed**

**Additional context**
vnc login -> login to blockchain
VNC_LC_API_KEY=xxxx vnc login -> login to LC without telling me I was already logged in to the blockchain
vnc n -> notarizes to the blockchain, but I am still logged in to the blockchain (token is in file, only context is set to LC)
vnc logout -> logouts from all of them

**Comment by dmacvicar** [comment]
Given that `vcn login` presents the credentials but there is no -lc flag required . What do you think if in that moment we tell the user always _where_ is she logging into?

```
vcn login
Logging to (host)
Email address:
```

**Comment by mmeloni** [comment]
We could returns more details on the environment in which the user logged in:
```
vcn login --lc-port 3324 --lc-host 127.0.0.1 --lc-no-tls
successfully logged in Codenotary Ledger Compliance
```
```
vcn login
email:
password:
successfully logged in Codenotary.io
```

**Comment by dmacvicar** [comment]
I think it is more useful to know in advance at least in the no --lc-host case, as vnc login takes a very bold default.
